USE [master]
GO

/****** Object:  Database [DBQLQuanAn]    Script Date: Thursday, 02, 08, 2018 11:39:40 PM ******/
CREATE DATABASE [DBQLQuanAn]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBQLQuanAn', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DBQLQuanAn.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBQLQuanAn_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DBQLQuanAn_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DBQLQuanAn] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBQLQuanAn].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBQLQuanAn] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBQLQuanAn] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBQLQuanAn] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBQLQuanAn] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBQLQuanAn] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBQLQuanAn] SET  MULTI_USER 
GO

ALTER DATABASE [DBQLQuanAn] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBQLQuanAn] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBQLQuanAn] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBQLQuanAn] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBQLQuanAn] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBQLQuanAn] SET QUERY_STORE = OFF
GO

USE [DBQLQuanAn]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DBQLQuanAn] SET  READ_WRITE 
GO

